name: Deploy master branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-dist --optimize-autoloader --no-dev"
      - run: composer require bref/bref

      - name: Serverless Deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:  ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Upload Assets & Run Migrations
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:  ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_PUBLIC_BUCKET: ${{ secrets.AWS_PUBLIC_BUCKET }}
        run: |
          aws s3 sync public/ s3://${{ secrets.AWS_PUBLIC_BUCKET }} --delete --exclude index.php
          ./vendor/bin/bref cli bref-dev-artisan -- migrate --force
